// src/App.jsx
import React, { useState } from 'react';
import axios from 'axios';

function formatTemp(t) {
  return Math.round(t) + '°C';
}

function MiniChart({ data }) {
  if (!data || data.length === 0) return null;
  const temps = data.map(d => d.temp);
  const min = Math.min(...temps);
  const max = Math.max(...temps);
  const width = 300;
  const height = 60;
  const points = temps.map((t, i) => {
    const x = (i / (temps.length - 1 || 1)) * width;
    const y = height - ((t - min) / (max - min || 1)) * height;
    return `${x},${y}`;
  }).join(' ');
  return (
    <svg width={width} height={height} className="sparkline" viewBox={`0 0 ${width} ${height}`}>
      <polyline points={points} fill="none" stroke="#1f77b4" strokeWidth="2" />
    </svg>
  );
}

export default function App() {
  const [q, setQ] = useState('');
  const [loading, setLoading] = useState(false);
  const [data, setData] = useState(null);
  const [error, setError] = useState(null);

  async function fetchWeather(e) {
    e && e.preventDefault();
    setError(null);
    if (!q) return setError('Enter a location');

    setLoading(true);
    try {
      const resp = await axios.get(`http://localhost:5000/api/weather?q=${encodeURIComponent(q)}`);
      setData(resp.data);
    } catch (err) {
      setError(err.response?.data?.error || err.message);
      setData(null);
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="container">
      <h1>Weather Forecast & Advisory</h1>

      <form onSubmit={fetchWeather} className="search-form" role="search">
        <input
          placeholder="Enter city (e.g. Mumbai, India)"
          value={q}
          onChange={(e) => setQ(e.target.value)}
          aria-label="Search location"
        />
        <button type="submit">{loading ? 'Loading...' : 'Get Weather'}</button>
      </form>

      {error && <div className="error" role="alert">{error}</div>}

      {data && (
        <div className="result">
          <h2>Location: {data.location.name}, {data.location.country}</h2>

          <div className="metrics">
            <div className="metric"><strong>Temp:</strong> {formatTemp(data.current.temp)}</div>
            <div className="metric"><strong>Humidity:</strong> {data.current.humidity}%</div>
            <div className="metric"><strong>Wind:</strong> {data.current.wind_kmh} km/h</div>
            <div className="metric"><strong>Short-term POP:</strong> {data.current.pop !== undefined ? data.current.pop + '%' : 'n/a'}</div>
          </div>

          <div className="chart-box">
            <h3>Short-term temperature trend</h3>
            <MiniChart data={(data.forecastList || []).slice(0, 12).map(item => ({ temp: item.main.temp }))} />
          </div>

          <div className="advisory-box">
            <h3>Advisories</h3>
            {data.advisories && data.advisories.length ? (
              data.advisories.map((a, i) => <div className="advice" key={i}>{a}</div>)
            ) : <div>No advisories</div>}
          </div>
        </div>
      )}

      <footer className="footer">
        <small>Data from OpenWeatherMap. Advisories generated by rule-based engine.</small>
      </footer>
    </div>
  );
}
